version: '3'

services:
  web:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://kanye:idk2327@db:5432/production
      JWT_SECRET: mySecret
  db:
    image: postgres
    environment:
      POSTGRES_USER: kanye
      POSTGRES_PASSWORD: idk2327
      POSTGRES_DB: production
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
